#!/usr/bin/env python

import sys
import logging

logging.basicConfig()
sys.path.insert(1, '/usr/local/lib/python2.7/site-packages')

from mykiss.application import Application

if __name__ == "__main__":
    try:
        app = Application(package="mykiss", 
                          version="0.1",
                          data_dir="/usr/local/share/mykiss",
                          log_level=logging.DEBUG)
    except Exception, e:
        sys.exit("Could not initialize application: %s" % str(e))
    app.run(sys.argv)
